baseURL = "https://wallpaper.bangunan.co/"
languageCode = "id"
title = "Wallpaper Dinding | Jasa Pasang Wallpaper Dinding Rapih dan Berpengalaman"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jasa Pasang Wallpaper Dinding - Profesional, Berpengalaman, dan Hasil yang Rapih"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jasa pasang wallpaper", "wallpaper dinding", "tukang wallpaper berpengalaman", "wallpaper interior", "wallpaper ruang tamu", "wallpaper kamar tidur"]
  base_price = 1500000
  price_range = 500000
  free_consultation = true
  service_types = [
  "Pasang Wallpaper Interior",
  "Pasang Wallpaper Custom",
  "Pasang Wallpaper Anti Air",
  "Pasang Wallpaper Kamar Tidur",
  "Pasang Wallpaper Ruang Tamu"
  ]
  categories = ["Jasa Wallpaper", "Tukang Pasang Wallpaper", "Wallpaper Dinding"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika tidak sesuai dengan kesepakatan.",
  "Pengembalian biaya jika hasil tidak memuaskan.",
  "Revisi gratis jika hasil pemasangan tidak rapih."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  service_output = "Ruangan dengan wallpaper yang terpasang rapih sesuai permintaan"

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jasa Pasang Wallpaper Dinding"
  hero_description = "Kami menawarkan layanan pemasangan wallpaper dinding berkualitas dengan hasil rapi dan tahan lama. Solusi terbaik untuk memperindah tampilan rumah, kantor, atau properti Anda, dilakukan oleh tim profesional dan berpengalaman."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Layanan Pasang Wallpaper"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan jasa pemasangan wallpaper dinding dengan kualitas pengerjaan terbaik dan biaya terjangkau. Anda bisa konsultasi secara gratis untuk membantu Anda memilih motif dan desain wallpaper yang sesuai dengan kebutuhan proyek Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "wallpaper.bangunan.co menawarkan jasa pemasangan wallpaper dinding berkualitas, dengan fokus pada ketelitian, keindahan, dan ketahanan. Kami berkomitmen memberikan kepuasan pelanggan dengan hasil yang rapi, cepat, dan tahan lama. Pilih kami untuk memenuhi kebutuhan dekorasi dinding rumah, kantor, atau properti Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Rudi|Agus|Fajar|Dedi|Hendra|Samsul}"
  message = "{Saya {menggunakan|memanfaatkan|memakai} jasa {pasang wallpaper|pemasangan wallpaper} dari wallpaper.bangunan.co untuk {rumah|hunian} saya, dan hasilnya {sangat memuaskan|benar-benar memuaskan|memuaskan sekali}. Pemasangannya {rapi|sangat rapi|terlihat profesional} dan hasilnya {sesuai harapan|tepat seperti yang saya inginkan|benar-benar sesuai ekspektasi}}."
  response = "{Terima kasih atas {kepercayaannya|kepercayaan kepada kami}! Kami {senang|gembira|bahagia} dapat memberikan hasil pemasangan wallpaper {yang memuaskan|yang sesuai harapan|berkualitas} untuk {rumah|hunian} Anda.|Kami sangat menghargai {kepercayaan|keyakinan} Anda. Senang dapat memberikan layanan {terbaik|berkualitas} untuk Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Ayu|Dewi|Lina|Maya|Putri|Ratna|Nina|Ika}"
  message = "wallpaper.bangunan.co {sangat membantu|benar-benar membantu|membantu sekali} dalam {memilih desain|memilih motif} dan {melakukan pemasangan|proses pemasangan} wallpaper di {rumah|hunian} saya. Hasilnya {sangat rapi|rapi sekali|benar-benar rapi} dan {sesuai dengan keinginan|sesuai harapan|tepat seperti yang saya harapkan}."
  response = "{Kami sangat menghargai ulasan Anda! {Senang|Bahagia} mendengar bahwa Anda {puas|terkesan|senang} dengan hasil pemasangan wallpaper kami.|Terima kasih atas {feedback|ulasannya}. Kami {gembira|bahagia} dapat memberikan {layanan|hasil} yang {memuaskan|berkualitas} untuk Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Budi|Eko|Rudi|Agus|Fajar|Dedi|Hendra|Samsul|Andi}"
  message = "Hasil pemasangan wallpaper dari wallpaper.bangunan.co {sangat rapi|rapi sekali|benar-benar rapi} dan {sesuai dengan harapan|memenuhi ekspektasi|seperti yang saya harapkan}. Pekerjaan {dilakukan dengan cepat|diselesaikan dengan efisien|diselesaikan tepat waktu} dan {profesional|sangat profesional}."
  response = "{Terima kasih! Kami {berkomitmen|berdedikasi} memberikan layanan pemasangan wallpaper {berkualitas|terbaik} dengan hasil {yang memuaskan|yang sesuai harapan}.|Terima kasih, atas {kepercayaannya|kepercayaan kepada kami}. Kami senang bisa memberikan hasil yang {terbaik|memuaskan} untuk Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Fajar|Eko|Joko|Budi|Rudi|Agus|Hendra|Dedi|Samsul}"
  message = "{Saya {sangat puas|merasa puas|benar-benar puas} dengan hasil {pasang|pemasangan} wallpaper dari wallpaper.bangunan.co. Dinding {terlihat lebih segar|menjadi lebih segar|tampak lebih bersih} dan {estetik|bernilai estetika tinggi|sangat estetik}}."
  response = "{Senang mendengar Anda {puas|senang|terkesan} dengan layanan kami. Terima kasih atas {kepercayaannya|kepercayaan kepada kami}!|Kami sangat senang mendengar {feedback|tanggapan} Anda. Terima kasih banyak!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Ayu|Dewi|Lina|Maya|Putri|Ratna|Nina|Ika}"
  message = "{Pelayanan|Layanan} wallpaper.bangunan.co {sangat memuaskan|benar-benar baik|memuaskan sekali}. Hasil pemasangan wallpaper {sangat berkualitas|berkualitas tinggi|luar biasa} dan {sesuai dengan yang saya harapkan|memenuhi ekspektasi|benar-benar sesuai harapan saya}."
  response = "{Terima kasih! Kami {senang|gembira} dapat membantu mewujudkan proyek pemasangan wallpaper Anda dengan {hasil terbaik|hasil berkualitas|hasil memuaskan}.|Kami sangat {menghargai|berterima kasih atas} {feedback|tanggapan} Anda. Terima kasih atas {kepercayaannya|kepercayaan kepada kami}}!"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Budi|Andi|Rudi|Agus|Fajar|Dedi|Hendra|Samsul|Joko}"
  message = "{Pemasangan|Proses pemasangan} wallpaper dari wallpaper.bangunan.co {sangat sesuai dengan|benar-benar memenuhi} {kebutuhan renovasi|keperluan renovasi|proyek renovasi} rumah saya. Pengerjaannya {cepat|tepat waktu|efisien} dan {rapi|bersih|sangat baik}."
  response = "{Kami senang mendengar bahwa Anda {puas|terkesan|sangat senang} dengan layanan kami. Terima kasih atas {ulasannya|feedback positifnya}!|Terima kasih atas {feedback|ulasannya}. Kami gembira dapat memberikan hasil yang {memuaskan|berkualitas tinggi|rapi dan cepat} untuk Anda.}"
  rating = 5

[[params.tabelItems]]
  name = "Pasang Wallpaper Ruang Tamu"
  price = "55.000 /m"
[[params.tabelItems]]
  name = "Pasang Wallpaper Kamar Tidur"
  price = "85.000 /m"
[[params.tabelItems]]
  name = "Pasang Wallpaper Anti Air"
  price = "100.000 /m"
[[params.tabelItems]]
  name = "Pasang Wallpaper Custom"
  price = "65.000 /m"
[[params.tabelItems]]
  name = "Pasang Wallpaper Seluruh Rumah"
  price = "55.000 /m"

[params.appliList]
  "Pasang Wallpaper Ruang Tamu" = "ruang tamu, area keluarga, ruang bersantai"
  "Pasang Wallpaper Kamar Tidur" = "kamar tidur utama, kamar tidur anak"
  "Pasang Wallpaper Anti Air" = "dapur, kamar mandi, area lembab"
  "Pasang Wallpaper Custom" = "ruangan dengan desain wallpaper khusus"
  "Pasang Wallpaper Seluruh Rumah" = "seluruh ruangan di rumah atau bangunan"

[params.kegunaanList]
  "Pasang Wallpaper Ruang Tamu" = "memberikan suasana yang nyaman dan elegan"
  "Pasang Wallpaper Kamar Tidur" = "menciptakan suasana tidur yang nyaman dan menenangkan"
  "Pasang Wallpaper Anti Air" = "melindungi dinding dari kelembapan dan kerusakan"
  "Pasang Wallpaper Custom" = "menghadirkan desain wallpaper yang unik dan personal"
  "Pasang Wallpaper Seluruh Rumah" = "memberikan keseragaman estetika di seluruh ruangan" 

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
title = "Jasa Pasang Wallpaper Dinding Berpengalaman | "
highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"